### ISSUE TITLE
Support special characters

### ISSUE THREAD

**Issue by pleonex** [sewave/hextractor#1]
Does the tool support special characters? It would be great if the tool could support them, like `á`, `é`, `ñ`, `¿`. In a quick look into the code I think it doesn't, and it converts into plain ASCII chars like `á -> a`. If it does support it, do I need to do something in special?

I think this is a mandatory requirement for any translation, so it would be great if the tool could handle it too!

Thanks!

**Comment by sewave** [comment]
Hi! 
I'm not used to github so I didn't see this issue earlier.
The default table maps acute characters to their ascii normal chars by default.
This is to be able to use them in the script even if I can't add them to the game (if I found a way I only have to change the table and reinsert).
You can use any utf8 character you want in your tables and they will work fine, but the viewer has issues with non-latin ones (but insertion and extraction works fine).
The default table is for convenience, because I can't always add the special char, but if you can, just change the character in the table it uses and will work fine (or you can create the tables from scratch, always in utf8 format).
The acute character is first because the last one in the table is the char that will be used for extraction.
Hope it helps!
